[package]
name = "shade-oracles-ensemble"
version = "0.1.0"
authors = ["sbeem <sbeem@pm.me>", "scrtreddev <scrtredev@protonmail.com", "hoomp <flammable.shower939@anonaddy.me>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
  "cached_contracts",
]

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10.0" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "0.10.0" }
cosmwasm-schema = "0.10.1"

shade-oracles = { path = "../shade_oracles" }

syn = { version="1.0.57",features=["full","fold"] }
quote = "1.0.8"

mock-band = { path = "../../contracts/mock_band" }
mock-sienna-pair = { path = "../../contracts/mock_sienna_pair" }
proxy-band-oracle = { path = "../../contracts/proxy_band_oracle" }
shade-staking-derivative-oracle = { path = "../../contracts/shade_staking_derivative_oracle" }
siennaswap-lp-oracle = { path = "../../contracts/siennaswap_lp_oracle" }
siennaswap-lp-spot-oracle = { path = "../../contracts/siennaswap_lp_spot_oracle" }
siennaswap-market-oracle = { path = "../../contracts/siennaswap_market_oracle" }
oracle-router = { path = "../../contracts/oracle_router" }
index-oracle = { path = "../../contracts/index_oracle" }
snip20-reference-impl = { git = "ssh://github.com/scrtlabs/snip20-reference-impl.git", branch = "master" }

fadroma = { branch = "v100", git = "https://github.com/hackbg/fadroma.git" }
