[package]
name = "shade-oracles-integration"
version = "0.1.0"
authors = [
  "sbeem <sbeem@pm.me>",
  "scrtreddev <scrtredev@protonmail.com",
  "hoomp <flammable.shower939@anonaddy.me>",
]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
  "cached_contracts",
]

[[bin]]
name = "deploy"
path = "src/deploy.rs"

[[bin]]
name = "local"
path = "src/local_deploy.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10.0" }
cosmwasm-math-compat = { tag = "v1.2.0", git = "https://github.com/securesecrets/shade.git" }
schemars = { version = "0.7" }
secret-toolkit = { version = "0.2", features = ["permit"] }

colored = "2.0.0"
shade-oracles = { version = "0.1.0", path = "../shade_oracles" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.67" }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
secretcli = { version = "0.1.0", git = "https://github.com/securesecrets/secret-plus-utils.git" }
